export class palabras {
    palabrasJuego = [
        "superfluo",
        "inefable",
        "inconmensurable",
        "etereo",
        "sempiterno",
        "petricor",
        "perenne",
        "luminiscencia",
        "mondo",
        "infinito",
        "ademan",
        "epoca",
        "bonhomia",
        "soledad",
        "resiliencia",
        "melancolia",
        "nefelibata",
        "melifluo",
        "elocuencia",
        "efervescencia",
        "ataraxia",
        "olvido",
        "iridiscencia",
        "limerencia",
        "ascendrado",
        "arrebol",
        "sonambulo",
        "serendipia",
        "alba",
        "epifania",
        "incandescencia",
        "nostalgia",
        "inmarcesible",
        "aurora",
        "desenlace"
        
    ];

}